### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by BenjaminZhouYJ** [hustvl/MSG-Transformer#2]
When can you release the pre-trained models？

**Comment by JaminFong** [comment]
Sorry that the pre-trained models cannot be transferred due to the institution's policy. It would be available if I could get some GPUs outside but this may take time to go. Could you please train them by yourself if possible? And welcome to contribute to the models!

**Comment by BenjaminZhouYJ** [comment]
Well, we do not have enough GPUs to train them on ImageNet :(

**Comment by JaminFong** [comment]
What a pity. If I could get enough GPUs, I will train and upload them. Please pay attention to the updates of the repo if needed. And thanks for your interest in our work!

Best

**Comment by BenjaminZhouYJ** [comment]
Thanks a lot!
